# -*- coding: utf-8 -*-
"""compute_statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzwEfTzTJrRYsJicKoojum2eoeF96LAj

# Ejercicio de programación 1: Compute statistics
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile compute_statistics.py
# """
# Ejercicio 1: Compute Statistics.
# Calcula estadísticas descriptivas a partir de un archivo.
# """
# 
# import sys
# import time
# 
# 
# def get_numbers_from_file(file_path):
#     """Leemos el archivo y extrae solo los datos numéricos válidos."""
#     numbers = []
#     try:
#         with open(file_path, 'r', encoding='utf-8') as file:
#             for line in file:
#                 try:
#                     numbers.append(float(line.strip()))
#                 except ValueError:
#                     print(f"Error: Dato inválido saltado: {line.strip()}")
#     except FileNotFoundError:
#         print(f"Error: El archivo {file_path} no existe.")
#     return numbers
# 
# 
# def calculate_stats(numbers):
#     """Realizamos los cálculos estadísticos usando algoritmos básicos."""
#     n_count = len(numbers)
#     if n_count == 0:
#         return None
# 
#     # Media
#     mean_val = sum(numbers) / n_count
# 
#     # Mediana
#     data = numbers[:]
#     for i in range(n_count):
#         for j in range(0, n_count - i - 1):
#             if data[j] > data[j + 1]:
#                 data[j], data[j + 1] = data[j + 1], data[j]
# 
#     if n_count % 2 == 0:
#         median_val = (data[n_count // 2 - 1] + data[n_count // 2]) / 2
#     else:
#         median_val = data[n_count // 2]
# 
#     # Moda
#     counts = {}
#     for num in numbers:
#         counts[num] = counts.get(num, 0) + 1
#     max_freq = max(counts.values())
#     mode_val = [k for k, v in counts.items() if v == max_freq][0]
# 
#     # Varianza y Desviación Estándar
#     variance_val = sum((x - mean_val) ** 2 for x in numbers) / n_count
#     std_dev_val = variance_val ** 0.5
# 
#     return mean_val, median_val, mode_val, variance_val, std_dev_val
# 
# 
# def main():
#     """Función principal: coordina la ejecución y guarda resultados."""
#     if len(sys.argv) < 2:
#         print("Uso: python compute_statistics.py fileWithData.txt")
#         return
# 
#     start_time = time.time()
#     file_name = sys.argv[1]
#     numbers = get_numbers_from_file(file_name)
# 
#     if not numbers:
#         return
# 
#     stats = calculate_stats(numbers)
#     mean, median, mode, var, std = stats
# 
#     end_time = time.time()
#     elapsed = end_time - start_time
# 
#     results = (
#         f"ARCHIVO: {file_name}\n"
#         f"Media: {mean:.4f}\n"
#         f"Mediana: {median:.4f}\n"
#         f"Moda: {mode:.4f}\n"
#         f"Varianza: {var:.4f}\n"
#         f"Desviación Estándar: {std:.4f}\n"
#         f"Tiempo: {elapsed:.6f} s\n"
#     )
# 
#     print(results)
#     # Req 2: Guardar en el archivo
#     with open("StatisticsResults.txt", "w", encoding='utf-8') as out_file:
#         out_file.write(results)
# 
# 
# if __name__ == "__main__":
#     main()

import os

# Lista de tus archivos de prueba
archivos = ["TC1.txt", "TC2.txt", "TC3.txt", "TC4.txt", "TC5.txt", "TC6.txt", "TC7.txt"]

print("="*50)
print("INFORME DE EJECUCIÓN - 7 CASOS DE PRUEBA")
print("="*50)

for f in archivos:
    if os.path.exists(f):
        print(f"\n>>> RESULTADOS PARA: {f}")
        # Ejecutamos el programa
        !python compute_statistics.py {f}

        # Respaldamos el resultado para evidencia
        nombre_resultado = f"Resultado_{f}"
        !cp StatisticsResults.txt {nombre_resultado}
        print(f"Copia guardada como: {nombre_resultado}")
        print("-" * 30)
    else:
        print(f"\n[!] ERROR: No se encontró el archivo {f}")

print("\nPRUEBAS COMPLETADAS.")

!pylint compute_statistics.py