# -*- coding: utf-8 -*-
"""convertNumbers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMaeP5X4TlvZEP_K_Q9OsH_lITapOIgc

## **Ejercicio de programación 2: Converter**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile convert_numbers.py
# """
# Ejercicio 2: Converter.
# Convierte numeros a binario y hexadecimal usando algoritmos basicos.
# """
# 
# import sys
# import time
# 
# 
# def to_binary(number):
#     """Convierte un numero a binario mediante divisiones sucesivas."""
#     if number == 0:
#         return "0"
#     binary = ""
#     temp_num = int(abs(number))
#     while temp_num > 0:
#         binary = str(temp_num % 2) + binary
#         temp_num //= 2
#     return binary if number >= 0 else "-" + binary
# 
# 
# def to_hexadecimal(number):
#     """Convierte un numero a hexadecimal mediante divisiones sucesivas."""
#     if number == 0:
#         return "0"
#     hex_chars = "0123456789ABCDEF"
#     hex_val = ""
#     temp_num = int(abs(number))
#     while temp_num > 0:
#         hex_val = hex_chars[temp_num % 16] + hex_val
#         temp_num //= 16
#     return hex_val if number >= 0 else "-" + hex_val
# 
# 
# def process_file_data(file_path):
#     """Lee el archivo y retorna la lista de resultados formateados."""
#     results = []
#     try:
#         with open(file_path, 'r', encoding='utf-8') as file:
#             item_count = 1
#             for line in file:
#                 data = line.strip()
#                 if not data:
#                     continue
#                 try:
#                     num = int(float(data))
#                     bin_res = to_binary(num)
#                     hex_res = to_hexadecimal(num)
#                     row = f"{item_count:<8} {num:<12} {bin_res:<15} {hex_res:<10}"
#                     results.append(row)
#                     item_count += 1
#                 except ValueError:
#                     print(f"Error: Dato invalido saltado: {data}")
#     except FileNotFoundError:
#         print(f"Error: Archivo {file_path} no encontrado.")
#     return results
# 
# 
# def main():
#     """Funcion principal: coordina la ejecucion y guarda resultados."""
#     if len(sys.argv) < 2:
#         print("Error: Se requiere un archivo de datos.")
#         return
#     start_time = time.time()
#     header = f"{'ITEM':<8} {'NUMBER':<12} {'BIN':<15} {'HEX':<10}"
#     data_rows = process_file_data(sys.argv[1])
#     if not data_rows:
#         return
#     end_time = time.time()
#     elapsed = end_time - start_time
#     # Construccion de salida final
#     final_results = [header] + data_rows
#     output_str = "\n".join(final_results)
#     output_str += f"\n\nTiempo de ejecucion: {elapsed:.6f} segundos\n"
#     print(output_str)
#     with open("ConvertionResults.txt", "w", encoding='utf-8') as out_file:
#         out_file.write(output_str)
# 
# 
# if __name__ == "__main__":
#     main()

import os

# Lista de tus archivos para el Ejercicio 2
archivos_ej2 = ["TC1.txt", "TC2.txt", "TC3.txt", "TC4.txt"]

print("="*50)
print("INFORME DE EJECUCIÓN - EJERCICIO 2")
print("="*50)

for f in archivos_ej2:
    if os.path.exists(f):
        print(f"\n>>> RESULTADOS PARA: {f}")
        # Ejecutamos el programa
        !python convert_numbers.py {f}

        # Guardamos copia para evidencia
        !cp ConvertionResults.txt Resultado_Conv_{f}
        print("-" * 30)
    else:
        print(f"\n[!] ERROR: No se encontró el archivo {f}")

print("\nPRUEBAS COMPLETADAS.")

!pylint convert_numbers.py